<?php

namespace Tests\Factory\Mock;

use Doctrine\Common\Collections\Collection;
use Framework\Factory\AbstractCommandFactory;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * Class CommandFactoryMock
 * @package Framework\Factory
 */
class CommandFactoryMock extends AbstractCommandFactory
{
    public function processCommands(array $names): Collection
    {

    }

    public function getContainer(): ContainerInterface
    {
        return parent::getContainer(); // TODO: Change the autogenerated stub
    }
}
