<?php

namespace Tests\Factory\Mock;

use Doctrine\Common\Collections\Collection;
use Framework\Factory\AbstractCommandFactory;
use Framework\Factory\AbstractVehicleFactory;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * Class VehicleFactoryMock
 * @package Framework\Factory
 */
class VehicleFactoryMock extends AbstractVehicleFactory
{
    public function processVehicles(array $names): Collection
    {
        // TODO: Implement processVehicles() method.
    }

    public function getContainer(): ContainerInterface
    {
        return parent::getContainer(); // TODO: Change the autogenerated stub
    }
}
